In [1]:
import numpy as np

In [2]:
# ARRAY OPERATIONS

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [4]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [5]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [7]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1 // a2

array([0, 0, 0, 0, 0])

In [9]:
a1** a2

array([      1,     128,    6561,  262144, 9765625])

In [10]:
# BROADCASTING

In [11]:
l = [10,20,30,40]
arr = np.array(l)

In [17]:
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [12]:
arr + 10

array([20, 30, 40, 50])

In [13]:
arr2= np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
arr2 = arr2 + 10
arr2

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45]])

In [18]:
arr2*2

array([[42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70],
       [72, 74, 76, 78, 80],
       [82, 84, 86, 88, 90]])

In [19]:
# Deep and shallow Copy

In [44]:
a = np.arange(1,21)

In [45]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
slice = a[:5]

In [47]:
slice

array([1, 2, 3, 4, 5])

In [48]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [49]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
a[4:6]*10

array([50, 60])

In [51]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
a 
b = a.copy() #shallow copy

In [53]:
b[0] = 99

In [54]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [55]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
# Matrix Operations


In [61]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [62]:
A

array([[1, 2],
       [3, 4]])

In [63]:
A*B

array([[ 5, 12],
       [21, 32]])

In [ ]:
A @ B #multiplication in matrix

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A,B) # multiplication in matrix

array([[19, 22],
       [43, 50]])

In [66]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
A.T #Transpose a matrix

array([[1, 3],
       [2, 4]])

In [71]:
# Stacking Array

In [73]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [74]:
b = np.arange(5,9)
b 

array([5, 6, 7, 8])

In [75]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [78]:
# Spliting Array

In [80]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [82]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]