In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = [1,2,3,4,5,"hello"]
a


[1, 2, 3, 4, 5, 'hello']

In [5]:
np.array(a)

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U11')

In [6]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [10]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [12]:
arr = np.linspace(1,5,100)
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [13]:
np.random.rand(10)

array([0.53830852, 0.05837803, 0.55388309, 0.9306153 , 0.10031723,
       0.10826123, 0.39601401, 0.70421084, 0.5040542 , 0.6608493 ])

In [14]:
np.random.randn(10)

array([-0.88270485, -0.10639364, -0.71773801, -0.0388465 ,  2.81815625,
       -2.45346568, -0.96298417,  0.41281158, -0.7987957 , -0.25740728])

In [15]:
np.random.randint(10,20,10)

array([10, 18, 16, 16, 18, 12, 13, 10, 11, 19])

In [16]:
## Array Attributes


In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size

9

In [20]:
arr.dtype

dtype('int32')

In [21]:
# Array Method

In [22]:
arr.min()

1

In [23]:
arr.max()

9

In [24]:
arr.sum()

45

In [25]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [26]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [27]:
arr.mean()

5.0

In [28]:
arr.std()

2.581988897471611

In [29]:
arr.argmax()

8

In [30]:
arr.argmin()

0

In [ ]:
#  Reshaping and Resizfing


In [31]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [35]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
# NUMPY INDEXING AND SLICING OF VECTORS

In [37]:
import numpy as np

In [39]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
arr[6]

17

In [41]:
arr[9]

20

In [42]:
arr[1:5]

array([12, 13, 14, 15])

In [43]:
arr[:5]

array([11, 12, 13, 14, 15])

In [44]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [46]:
arr[3::2]

array([14, 16, 18, 20])

In [47]:
# NUMPY INDEXING AND SLICING OF MATRIX

In [49]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [50]:
arr[0]

array([1, 2, 3, 4, 5])

In [51]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [52]:
arr[5]

array([26, 27, 28, 29, 30])

In [54]:
arr[0][4]

5

In [55]:
arr[0,0]

1

In [56]:
arr[0,4]

5

In [57]:
arr[5,4]

30

In [59]:
slice  = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [61]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [62]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [63]:
# BOOLEAN INDEXING

In [70]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [71]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [72]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])